### ISSUE TITLE
docker build fails

### ISSUE THREAD

**Issue by dogancanbakir** [vzarytovskii/haskell-devcontainer#7]
I've tried both locally and with GitHub actions, but the build fails. This the err I got,
`ERROR: failed to solve: process "/bin/sh -c cabal install --haddock-hoogle -v     haskell-dap-0.0.15.0     ghci-dap-0.0.17.0     haskell-debug-adapter-0.0.35.0     hlint-3.3.6     apply-refact-0.9.3.0     retrie-1.1.0.0     hoogle-5.0.18.3     ormolu-0.3.1.0" did not complete successfully: exit code: 1`

and this is the link to the GitHub action build, https://github.com/dogancanbakir/haskell-dev-env/actions/runs/3074588897/jobs/4967463449#step:5:21796

I've tried different versions of those packages and a combination of this dev container and the official one but couldn't make it work. 

Am I missing something?

**Comment by vzarytovskii** [comment]
I'll look at it on Monday, looks odd indeed.

**Comment by vzarytovskii** [comment]
> and this is the link to the GitHub action build, [dogancanbakir/haskell-dev-env/actions/runs/3074588897/jobs/4967463449#step:5:21796](https://github.com/dogancanbakir/haskell-dev-env/actions/runs/3074588897/jobs/4967463449#step:5:21796)

~Hm, interesting, it seems it can't install dap package (it seems thought it is downgraded to 0.0.15.0 from 0.0.17.0) . I have some different issues locally though.~

**Update:** Ok, it is the same issue for me now.

**Comment by vzarytovskii** [comment]
I pinned `fsnotify` package which is a dependency for the dap, and introduced a breaking change recently.
Let's see if it fixes it.

**Comment by vzarytovskii** [comment]
Yeah, this works:
https://github.com/vzarytovskii/haskell-dev-env/actions/runs/3082669375/jobs/4982650423

**Comment by dogancanbakir** [comment]
Well done, thanks!
